### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by orestis-z** [cozycodegh/cordova-plugin-inapppurchases#1]
First of all thanks for coding up this lib. It's the only working one that I could find after a lot of digging. 🙏

Possibly the same issue that was fixed here? https://github.com/RainerAppel/cordova-plugin-inapppurchase/compare/master...richmoh:cordova-plugin-inapppurchase:master

Stack trace:
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{<packagename>/com.android.billingclient.api.ProxyBillingActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.IntentSender android.app.PendingIntent.getIntentSender()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.IntentSender android.app.PendingIntent.getIntentSender()' on a null object reference
       at com.android.billingclient.api.ProxyBillingActivity.onCreate(ProxyBillingActivity.java:121)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Here's the raw stacktrace from crashlytics: [stacktrace.txt](https://github.com/cozycodegh/cordova-plugin-inapppurchases/files/10683752/stacktrace.txt)

<img width="471" alt="Screenshot 2023-02-08 at 10 16 28" src="https://user-images.githubusercontent.com/23146389/217486802-f65ba221-a129-4eff-bd0b-f33773795456.png">

**Comment by cozycodegh** [comment]
Thanks, I'm still trying to make it easier to find by Google.

Appreciate the links. Those calls are now done by the Android Billing Library 5 itself and it seems some people get the same issue as you outside of using cordova. 
These might help:
https://github.com/stripe/stripe-android/issues/777
https://stackoverflow.com/questions/21932574/from-second-time-in-app-purchase-throwing-exception-in-android
It sounds like this might happen rarely when trying to purchase something that has already been purchased successfully.

Does the plugin return an error message that you can respond to?

**Comment by orestis-z** [comment]
@cozycodegh thanks for you quick reply!
It doesn't return an error message and leads to a crash :(
My guess is that it would need to be handled in the android native side of the plugin so that somebody can handle it on the javascript side (without the whole app crashing)

**Comment by cozycodegh** [comment]
Some debugging questions:
Does the same crash happen when you have included the plugin, but not made any calls?
Or does it only occur after certain calls to the plugin are made?
Has the Google Play pop up come up?
I haven’t been able to reproduce the error.

**Comment by orestis-z** [comment]
Unfortunately, it's a bit of a black box. I can't reproduce it either. I have only the crash report posted above from crashlytics...

**Comment by cozycodegh** [comment]
It looks like an uncommon crash that has something to do with a background process closing, and the billing library crashing afterwards… It could have something to do with the app switching to show a full screen ad. 
I'll close this if I can't reproduce, but please re-open the issue if it's happening again, or more to go on for debugging.

**Comment by orestis-z** [comment]
Sweet makes sense

**Comment by orestis-z** [comment]
Sweet makes sense!

**Comment by marcellov7** [comment]
**com.android.billingclient.api.ProxyBillingActivity.onCreate** 
 
OS version: android8.1.0
Model:Nexus 5X

```
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.****/com.android.billingclient.api.ProxyBillingActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.IntentSender android.app.PendingIntent.getIntentSender()' on a null object reference
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2778)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:807)
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'android.content.IntentSender android.app.PendingIntent.getIntentSender()' on a null object reference
com.android.billingclient.api.ProxyBillingActivity.onCreate (com.android.billingclient:billing@@6.0.1:14)
android.app.Activity.performCreate (Activity.java:7009)
android.app.Activity.performCreate (Activity.java:7000)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1214)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2731)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2856)
android.app.ActivityThread.-wrap11
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1589)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:164)
android.app.ActivityThread.main (ActivityThread.java:6494)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:807) 
```

Could it be related to Google's automated bot tests during testing?

**Comment by cozycodegh** [comment]
It’s a crash in the Google Play Billing Library, and some people say it’s come up on app users’ devices outside of testing.
